server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: www.xiaowenshu.cn:9092
    producer:
      #      发生错误后,消息重复发的次数
      retries: 0
      #      当有多个消息需要被发送到同一个分区时,生产者会把他们放在同一个批次内.该参数指定了一个批次可以使用的内存大小
      batch-size: 16384
      #      设置生产者内存缓冲的大小
      buffer-memory: 33554432
      #      键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      ack
      #       all:必须收到消息
      #       0:不等待响应
      #       1:收到 1 至多条消息
      acks: 1

    consumer:
      #      自动提交的时间间隔,在 springboot 2.x 的版本当中采用的值类型为 Duration 需要符合特定的格式,如：1S,1M,2H,5D
      auto-commit-interval: 1S
      #      auto-offset-reset 指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      #      latest:默认值.在偏移量无效的情况下,消费者将从最新的记录开始读取数据(在消费者启动之后生成的记录)
      #      earliest:在偏移量无效的情况下,消费者将从起始位置读取分片信息
      auto-offset-reset: earliest
      #      是否自动提交偏移量,默认值是 true ,为了避免出现重复数据和丢失,可以将其设置为 false ,然后手动提交偏移量
      enable-auto-commit: false
      #      键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      #      值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      #      在侦听器容器中运行的线程数
      concurrency: 5
      #      listener 负责 ack ,每调用一次,就立即 commit
      ack-mode: manual_immediate
      missing-topics-fatal: false