#spring:
#  application:
#    name: dubbo-springboot-provider
server:
  port: 8091

dubbo:
  application:
    name: dubbo-springboot-provider
  registry:
    address: zookeeper://www.xiaowenshu.cn:2181
#    protocol: zookeeper
  protocol:
    name: dubbo-springboot
    port: 20880
  provider:
    timeout: 1000